FROM python:3.9-slim

# Install dependencies
RUN pip install confluent_kafka

# Copy script to the container
COPY main.py /app/main.py
WORKDIR /app

# Set entrypoint
ENTRYPOINT ["python3", "main.py"]
